---
title: "SNAP Project"
author: "Yangyang Dai"
#date: "2/1/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library("ggplot2")
theme_set(theme_bw())
library("sf")
library(RColorBrewer)
library(fmsb)
library(plotly)
library(MASS)
library(mosaic)
library(knitr)
library(tidyverse)
library(ggformula)
library(gridExtra)
library(broom)
library(binom)
library(scales)
require(xlsx)
library(gtable)
library(grid)
require("devtools")
library("tidyverse")
library("viridis")
library("urbnmapr")
library(data.table)
library(scales)
library(lubridate)
library(dplyr)
```
```{r include=FALSE}
county <- st_read("cb_2017_us_county_500k/cb_2017_us_county_500k.shp",stringsAsFactors=FALSE)
# glimpse(county)
county_ll <- st_transform(county, "+proj=longlat +ellps=WGS84 +datum=WGS84")
# st_coordinates(county_ll)
retailer <- read_csv("store_locations_2019_01_29.csv")
retailer$County<-paste(retailer$County, "COUNTY", sep=" ")
# glimpse(retailer)
dt <- read.delim("2015Jan_ggplot2Koffman.txt",sep=',',header = FALSE,colClasses = "character")
dt <- mutate_all(dt, funs(toupper))
colnames(dt)=c("state","statefp","countyfp","name","loc")
# head(dt)
merged_data <- left_join(county, dt, by = c("COUNTYFP"="countyfp"))
merged_data <- left_join(merged_data, retailer, by = c("name"="County"))

glimpse(merged_data)

# class(merged_data)
# head(county)

coords <- st_coordinates(merged_data)
coords<-data.frame(coords)

ggplot() + geom_polygon(data = merged_data, aes(x = X, y = Y), colour = "black", fill = NA)
```

```{r}

ggplot(merged_data, aes(x = X, y = Y)) +
    geom_polygon(colour = "black", size = 1, fill = "white") +
    geom_point(aes(x = Longitude, y = Latitude), size = 0.2, shape = 21, colour = "black")


state <- st_read("cb_2017_us_state_500k/cb_2017_us_state_500k.shp",stringsAsFactors=FALSE)

ggplot() + geom_sf(data = merged_data) 

# p + geom_point(data=d, aes(x=lon, y=lat),size=5)
# 
# coords <- st_coordinates(county_ll)
# coords<-data.frame(coords)
# ggplot() + geom_polygon(data = coords, aes(x = X, y = Y), colour = "black", fill = NA)

```















