---
title: "SNAPMaps"
author: "Yangyang Dai"
date: "2/8/2019"
output: html_document
---

```{r setup, include=FALSE}
library("ggplot2")
theme_set(theme_bw())
library("sf")
library(RColorBrewer)
library(fmsb)
library(plotly)
library(MASS)
library(mosaic)
library(knitr)
library(tidyverse)
library(ggformula)
library(gridExtra)
library(broom)
library(binom)
library(scales)
require(xlsx)
library(gtable)
library(grid)
require("devtools")
library("tidyverse")
library("viridis")
library("urbnmapr")
library(data.table)
library(scales)
library(lubridate)
devtools::install_github("UrbanInstitute/urbnmapr")

```

```{r include=FALSE}
library(sf) ## Simple Features
library(tidyverse)
library(magrittr)
library(ggplot2)
library(tidycensus)
require(grid)

## Consider:
# path.package("sf")
# install.packages("sf", lib="Resources/library/sf0_7_3")
# library(sf, lib.loc="Resources/library/sf0_7_3")


## Quick theme for removing extraneous chart parts with theme_get:
## https://www.rdocumentation.org/packages/ggplot2/versions/3.1.0/topics/theme_get
theme_clean_map <- function(base_size = 12) {
  
  theme_void(base_size) %+replace%
    theme(
      axis.title      =   element_blank(),
      axis.text       =   element_blank(),
      axis.ticks       =   element_blank(),
      panel.background    =   element_blank(),
      panel.grid      =   element_blank(),
      panel.grid.major =  element_line(size = 0),
      panel.grid.minor = element_blank(),
      panel.spacing    =   unit(0,"lines"),
      plot.margin     =   unit(c(0,0,0,0),"lines"),
      complete = TRUE
    )
}
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
county <- st_read("cb_2017_us_county_500k/cb_2017_us_county_500k.shp")
head(county)
# plot(county)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
retailer <- read_csv("store_locations_2019_01_29.csv")
head(retailer)
```
```{r}
ggplot() +
  geom_sf(data=county) +
  geom_point(data=retailer, aes(x=Longitude, y=Latitude), alpha=0.5) +
  scale_color_manual(values=c("#1696d2", "#fdbf11")) +
  theme_clean_map()

# ggplot() + 
#   geom_sf(data=county) + 
#   scale_fill_distiller(type = "seq", palette = 6, direction=1) + 
#   geom_point(data=retailer, aes(x=Longitude, y=Latitude), alpha=0.9) + 
#   scale_color_manual(values=c("#1696d2", "#fdbf11")) + 
#   theme_clean_map()
```




```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot() + 
  geom_sf(data=county, color = "#ffffff") + 
  scale_fill_distiller(type = "seq", palette = 6, direction=1) + 
  geom_point(data=retailer, aes(x=Longitude, y=Latitude), alpha=0.9) + 
  # scale_color_manual(values=c("#1696d2", "#fdbf11")) + 
  theme_clean_map()

```

```{r}
# nc3_points <- st_point_on_surface(county)
# nc3_coords <- as.data.frame(sf::st_coordinates(nc3_points))
# nc3_coords$NAME <- county$NAME
# ggplot() + geom_sf(data = county) + geom_sf(data = county, aes(fill = STATEFP)) +
#   geom_text(data = nc3_coords, aes(X, Y, label = NAME), colour = "white")
```

```{r}
theme_set(theme_bw())
library("sf")

ggplot(data = county) +
    geom_sf(fill="#4b78af") +
    geom_point(data = retailer, aes(x = Longitude, y = Latitude), size = 0.00001, 
        shape = 23, fill = "white") +
      coord_sf(xlim = c(-130, -65), ylim = c(20, 55), expand = FALSE) +
  labs(title="Retailer Stores Participated in SNAP", subtitle="Retailer Stores are heavily distributed in Midwest and East", caption="Source:USDA Food Nutrition Services")+
  theme(plot.caption = element_text(hjust = 0),
        legend.text = element_text(size = 8),
        legend.title=element_text(size=6,face="bold"),
        plot.title=element_text(size=17, 
                                    face="bold", 
                                    family="American Typewriter",
                                    color="black",
                                    hjust=0.5,
                                    lineheight=1.2),  # title
            plot.subtitle=element_text(size=12, 
                                       family="American Typewriter",
                                       hjust=0.5),
 axis.title.x=element_blank(), 
 axis.text.x=element_blank(),
 axis.ticks.x=element_blank(),
 axis.title.y=element_blank(), 
 axis.text.y=element_blank(),
 axis.ticks.y=element_blank(),
 panel.background=element_blank(),
 panel.border=element_blank(),
 panel.grid.minor=element_blank(),
 plot.background=element_blank(),
 legend.position = c(.95, .5))


# + 
#   geom_text(data= world_points,aes(x=X, y=Y, label=name), color = “darkblue”, fontface = "bold", check_overlap = FALSE) + 
#   annotate(geom = "text", x = -90, y = 26, label = “Gulf of Mexico”, fontface = italic”, color = “grey22”, size = 6) + 
#   annotation_scale(location = “bl”, width_hint = 0.5) + 
#   annotation_north_arrow(location = “bl”, which_north = “true”, pad_x = unit(0.75, “in”), pad_y = unit(0.5, “in”), style = north_arrow_fancy_orienteering) + 
#   coord_sf(xlim = c(-162, -79), ylim = c(20, 65), expand = FALSE) + xlab(“Longitude”) +
#   ylab(“Latitude”) + 
#   ggtitle(“Map of the Gulf of Mexico and the Caribbean Sea”) + 
#   theme(panel.grid.major = element_line(color = gray(.5), linetype = “dashed”, size = 0.5), panel.background = element_rect(fill = “aliceblue”))
#                  


```



