---
title: "SNAP"
author: "Yangyang Dai"
fontsize: 11pt
output:
  pdf_document:
    df_print: kable
fig_crop: false

geometry: margin=0.75in
---


```{r setup, include=FALSE}
library(MASS)
library(mosaic)
library(knitr)
library(tidyverse)
library(ggformula)
library(gridExtra)
library(broom)
library(binom)
options(width=70, digits=4, scipen=8)
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
# Set R output size a bit smaller than default
opts_chunk$set(size='small') 
# Set the default to NOT display R code
#opts_chunk$set(echo=FALSE) 

```

# Participation by state
```{r echo=FALSE}
require(xlsx)
# skip first 6 rows, and only read in 1st and 4th col
part_18 <-read.xlsx("snap_part_2018.xls",header=F,skip=6,sheetIndex = 1)[-c(3,43),][1:53,]
colnames(part_18) <- c("state","sep17","aug18","sep18","sep18_vs_aug18","sep18_vs_sep17")
#head(part_18)
```


```{r echo=FALSE}
r1="Northeast"
r2="Midwest"
r3="South"
r4="West"

s1<-c("Connecticut", "Maine", "Massachusetts", "New Hampshire", "Rhode Island", "Vermont", "New Jersey", "New York","Pennsylvania")
s2<-c("Illinois", "Indiana", "Michigan", "Ohio", "Wisconsin", "Iowa", "Kansas", "Minnesota", "Missouri", "Nebraska", "North Dakota", "South Dakota")
s3<-c("Delaware", "Florida", "Georgia", "Maryland", "North Carolina", "South Carolina", "Virginia", "District of Columbia", "Alabama", "Kentucky", "Mississippi", "Tennessee", "Arkansas", "Louisiana", "Oklahoma", "Texas")
s4<-c("Arizona", "Colorado", "Idaho", "Montana", "Nevada", "New Mexico", "Utah", "Wyoming","Alaska", "California", "Hawaii", "Oregon", "Washington")

#part_18$region <- NA
for (row in 1:nrow(part_18)) {
  state <- part_18[row, "state"]
  #region <- part_18[row, "region"]
  if (state %in% s1) {
  region = r1
}else if(state %in% s2){
  region = r2
}else if(state %in% s3){
  region = r3
}else if(state %in% s4) {
  region = r4
}
  part_18$region[row] <- region}

#head(part_18)
```


```{r echo=FALSE}
#sapply(part_18, class)
#part_18$sep18
#as.numeric(part_18$sep18)
#library(Hmisc) # cut2
#split(part_18, cut(part_18$sep18, 6))
#part_18<-part_18[part_18$sep18!="--", ]
#apply(part_18,2,max)
#apply(part_18,2,min)
```

```{r}
#part_18$sep18
```


```{r echo=FALSE}
library(scales)
part_18 <- part_18[!grepl("Guam", part_18$state),]
#y <- apply(as.matrix(part_18[, 4]), 2, as.numeric)
#part_18["sep18"] <- as.numeric(levels(part_18["sep18"]))
#part_18 %>% group_by(region) %>% arrange(sep18, state) %>%
ggplot(data=part_18,aes(x=reorder(state,as.numeric(sep18)),as.numeric(sep18)),fill="steel blue") + scale_y_continuous(labels=c("0","2m","4m","6m"))+geom_col() + coord_flip() +  facet_grid(region~.,scales="free_y") +
  labs(x = "state", y = "Participation population 2018",
       title="US SNAP Participation by State in 2018", subtitle="SNAP participation population has huge range across states in different regions", caption = "Source: https://www.fns.usda.gov/pd/supplemental-nutrition-assistance-program-snap") +
  theme( axis.text=element_text(color="black"), strip.text.y=element_text(size=9), strip.background=element_rect(fill="white"), panel.grid.major.y=element_blank(), panel.grid.minor.x=element_blank(), axis.ticks=element_blank()) 
```


```{r echo=FALSE}
#library(usmap)
#library(ggplot2)

#plot_usmap(regions = "states") + 
 # labs(title = "US Counties", subtitle = "This is a blank map of the counties of the United States.") + 
  #theme(panel.background = element_rect(colour = "black", fill = "lightblue"))

#part_18["sep18"] <- as.numeric(levels(part_18["sep18"]))
#plot_usmap(data = part_18, values = "sep18", lines = "red") + 
 # scale_fill_continuous(name = "SNAP Participation (2018)", label = scales::comma) + 
  #theme(legend.position = "right")

```


# national participation overtime
# u/m overtime

```{r echo=False}
part_ben<-read.xls("part_ben_89to18.xlsx",header=TRUE,sep = ",", dec = ".")
head(part_ben)
um<-read.xls("um_79to18.xlsx")
#head(um)
```
```{r echo=FALSE}
#18806463/50
#ggplot(part_ben, aes(x = Year, y = Participation.number.)) + 
 # geom_line() +
  #scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  #theme_minimal()


library(ggplot2)
library(gtable)
library(grid)
grid.newpage()

p <- ggplot(part_ben, aes(x = Year))
  p <- p + geom_line(aes(y = Benefit.dollar.person., colour = "Benefit dollar person"),size=1)
  
  # adding the relative humidity data, transformed to match roughly the range of the temperature
  p <- p + geom_line(aes(y = Participation.number./300000, colour = "Participation number"),size=1)
  
  # now adding the secondary axis, following the example in the help file ?scale_y_continuous
  # and, very important, reverting the above transformation
  p <- p + scale_y_continuous(sec.axis = sec_axis(~.*300000, name = "Participation number"))
  # modifying colours and theme options
  p <- p + scale_colour_manual(values = c("blue", "red"))
  p <- p + scale_x_continuous(breaks=c(1990,1995,2000,2005,2010,2015))
  p <- p + labs(y = "Dollar",
                x = "Year",
                colour = "Parameter",title="SNAP participation population and benefit dollar per person 1989-2018", subtitle="Overall the SNAP participation and benefits increased over the last two decades",caption="Source:https://data.bls.gov/timeseries/LNS14000000")
  p <- p + theme(legend.position = c(0.7, 0.9))
p
```


```{r echo=FALSE}
library(ggplot2)

snap_event<-read.xls("snap_event.xlsx",head=T)
#head(snap_event)
part_ben$Year <- as.Date(as.character(part_ben$Year), format = "%Y")
snap_event$year <- as.Date(as.character(snap_event$year), format = "%Y")

#presidential <- presidential[-(1:3),]
yrng <- range(part_ben$Participation.number.)
ymin <- yrng[1]
ymax <- yrng[1] + 0.1*(yrng[2]-yrng[1])

p2 <- ggplot()
p2 <- p2 + geom_line(mapping=aes(x=Year, y=Participation.number.), data=part_ben , size=2, alpha=0.5) 
p2 <- p2 + scale_x_date("time") +  scale_y_continuous(name="participation")
p2 <- p2 + geom_segment(mapping=aes(x=year,y=ymin, xend=year, yend=ymax, colour=event), data=snap_event, size=2, alpha=0.5)
p2 <- p2 + geom_point(mapping=aes(x=year,y=ymax, colour=event ), data=snap_event, size=0.3) 
p2 <- p2 + geom_text(mapping=aes(x=year, y=ymax, label=event, angle=30, hjust=-0.1, vjust=0.1),size=1.5, data=snap_event) + labs(title="SNAP History and participation", subtitle="Food act events drive the participation of SNAP", caption="Source:https://www.fns.usda.gov/snap/short-history-snap")
p2
```




